#include "GimbalControllerSettings.h"

DECLARE_SETTINGGROUP(GimbalController, "GimbalController")
{
}

DECLARE_SETTINGSFACT(GimbalControllerSettings, EnableOnScreenControl)
DECLARE_SETTINGSFACT(GimbalControllerSettings, ControlType)
DECLARE_SETTINGSFACT(GimbalControllerSettings, CameraVFov)
DECLARE_SETTINGSFACT(GimbalControllerSettings, CameraHFov)
DECLARE_SETTINGSFACT(GimbalControllerSettings, CameraSlideSpeed)
DECLARE_SETTINGSFACT(GimbalControllerSettings, showAzimuthIndicatorOnMap)
DECLARE_SETTINGSFACT(GimbalControllerSettings, toolbarIndicatorShowAzimuth)
DECLARE_SETTINGSFACT(GimbalControllerSettings, toolbarIndicatorShowAcquireReleaseControl)
DECLARE_SETTINGSFACT(GimbalControllerSettings, joystickButtonsSpeed)
DECLARE_SETTINGSFACT(GimbalControllerSettings, zoomMaxSpeed)
DECLARE_SETTINGSFACT(GimbalControllerSettings, zoomMinSpeed)
DECLARE_SETTINGSFACT(GimbalControllerSettings, joystickGimbalEnabled)
DECLARE_SETTINGSFACT(GimbalControllerSettings, joystickGimbalShowUI)
DECLARE_SETTINGSFACT(GimbalControllerSettings, joystickGimbalPitchAxisIndex)
DECLARE_SETTINGSFACT(GimbalControllerSettings, joystickGimbalYawAxisIndex)
DECLARE_SETTINGSFACT(GimbalControllerSettings, joystickGimbalDeadband)
DECLARE_SETTINGSFACT(GimbalControllerSettings, joystickGimbalExpo)
DECLARE_SETTINGSFACT(GimbalControllerSettings, joystickGimbalSmoothing)
DECLARE_SETTINGSFACT(GimbalControllerSettings, joystickGimbalSendRateHz)
DECLARE_SETTINGSFACT(GimbalControllerSettings, joystickGimbalPitchLimit)
DECLARE_SETTINGSFACT(GimbalControllerSettings, joystickGimbalYawLimit)
